export const shopdata = [
  {
    heading: "Product Categories",
    categories: [
      "DAW'S",
      "Expansions",
      "Free Downloads",
      "KONTAKT LIBRARIES",
      "Plug-ins",
      "synthesizer",
      {
        heading: "SAMPLE PACKS",
        subcategories: [
          "Ambient",
          "Bass",
          "Bundles",
          "Cinematic",
          "Dancehall",
          "Deep House",
          "Disco",
          "Drums",
          "Dubstep",
          "EDM",
          "Electronica",
          "Ethnic",
          "Funk",
          "Future RnB",
          "Guitar",
          "Hardstyle",
          "Hip Hop",
          "House",
          "Kicks",
          "Latin",
          "Live Instruments",
          "Minimal Techno",
          "Piano",
          "Pop",
          "Reggaeton",
          "Rock",
          "Sound Effect",
          "Synthwave",
          "Tech House",
          "Techno",
          "Trance",
          "Trap",
          "Tropical House",
          "Vocals",
        ],
      },
      "Other",
    ],
  },
  {
    heading: "Brand",
    brands: [
      "Ample Sound",
      "iZotope",
      "Native Instruments",
      "XLN Audio",
      "Spectrasonics",
      "Toontrack",
    ],
  },
];
